### ISSUE TITLE
Allow newtype pattern instead of type aliasing

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/cddl-codegen#44]
Suppose you have the following CDDL

```protocolMagic = u32```

(I think this happens on anything that's a primitive?)

# Current behavior

```rust
type ProtocolMagic = u32;
```

# (Occasionally) Desired behavior

```rust
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize, JsonSchema)]
pub struct ProtocolMagic(pub u32);
```

**Comment by rooooooooob** [comment]
How do we want to specify for which types this happens? A flag like --newtypes=protocolMagic,otherType? or a switch on/off globally?

**Comment by SebastienGllmt** [comment]
yeah not to sure how we want to do this since a global flag doesn't seem so helpful either, but we didn't build any way to annotate codegen hints in comments either
