### ISSUE TITLE
Enums are not public?

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/cddl-codegen#46]
For some reason, all structs are `pub struct` but all the structs are just `enum` (not public)

I understand that non-C type Rust enums can't be exported via WASM, but this shouldn't be an issue because these enums aren't marked with `#[wasm_bindgen]` anyway

Note: this may already be solved by the codegen v2 in latest master since I'm using an old version at the moment

**Comment by rooooooooob** [comment]
This is already resolved in `master`. They were made public as part of the wasm/rust split to make the codegen more rust-usage-friendly.
