### ISSUE TITLE
Crash on array of non-choice element that has multiple fields

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/cddl-codegen#62]
From byron.cddl

```
block = [0, ebblock]
      / [1, mainblock]
```

**Comment by rooooooooob** [comment]
@SebastienGllmt we support the equivalent of:
```
block = [0, ebblock // 1, mainblock]
```

Or something like that using group choices instead of type choices. Obviously we should support the type choice one too at some point. There's an example very similar in the Shelley CDDL iirc
